version: '3.8'

services:
  java_api:
    container_name: java_api
    image: 'cuentamovimientos_api:latest'
    restart: on-failure
    env_file: ./.env
    build:
      context: .
    ports:
      - 6868:8080
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://java_db:3307/inventory_db
      - SPRING_DATASOURCE_USERNAME=mysql
      - SPRING_DATASOURCE_PASSWORD=1234
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.MySQL8Dialect
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=com.mysql.cj.jdbc.Driver
    depends_on:
      - java_db

  java_db:
    container_name: java_db
    image: mysql:latest
    restart: on-failure
    environment:
      MYSQL_DATABASE: 'inventory_db'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'lucho'
      # You can use whatever password you like
      MYSQL_PASSWORD: '1234'
      # Password for root access
      MYSQL_ROOT_PASSWORD: '1234'
    ports:
      # <Port exposed> : <MySQL Port running inside container>
      - '3307:3306'
    expose:
      # Opens port 3306 on the container
      - '3307'
      # Where our data will be persisted
    volumes:
      - db-data:/var/lib/mysql
volumes:
  db-data:
    driver: local